const styles = {
  container: {
    position: 'relative',
    width: '100vw',
    height: '100vh',
    backgroundColor: '#0b4a0b',
    overflow: 'hidden',
  },
  playerHand: {
    position: 'absolute',
    bottom: 20,
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: 8,
  },
  playerCard: {
    width: 60,
    height: 90,
    borderRadius: 8,
    color: 'white',
    fontWeight: 'bold',
    fontSize: 20,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    userSelect: 'none',
  },
  botHandContainer: {
    display: 'flex',
  },
  cardRow: {
    display: 'flex',
    gap: 6,
  },
  cardRowVertical: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  rotatedCardRight: {
    transform: 'rotate(-90deg)',
    marginTop: '-30px',
  },
  rotatedCardLeft: {
    transform: 'rotate(90deg)',
    marginTop: '-30px',
  },
  centerArea: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 100,
    height: 140,
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  discardPile: {
    width: 80,
    height: 120,
    borderRadius: 10,
    color: 'white',
    fontWeight: 'bold',
    fontSize: 30,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    userSelect: 'none',
    boxShadow: '0 0 10px rgba(0,0,0,0.5)',
  },
  drawButton: {
    marginTop: 12,
    padding: '6px 12px',
    borderRadius: 8,
    border: 'none',
    backgroundColor: ' #999999',
    color: 'white',
    cursor: 'pointer',
  },
  winnerBanner: {
    position: 'absolute',
    top: 20,
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    padding: 20,
    borderRadius: 10,
    zIndex: 20,
    textAlign: 'center',
  },
  colorPicker: {
    position: 'absolute',
    top: '40%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 8,
    boxShadow: '0 0 10px rgba(0,0,0,0.3)',
    zIndex: 30,
  },
  colorButton: {
    width: 40,
    height: 40,
    margin: 4,
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
  },
  countdownOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.7)', 
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100, 
  },
  countdownText: {
    fontSize: 72, 
    fontWeight: 'bold',
    color: 'white',
  },
};

export default styles;